### PR TITLE
Use an alternate method of reading column details if the old way fails

### LINKED ISSUE #70: Database entity blank
After generated Laravel ER diagram successfully, it shows the tables relationship but didn't show database entity.

table

### PR DESCRIPTION
**Pull request by mrunkel**
I basically used the solution from https://github.com/beyondcode/laravel-er-diagram-generator/issues/70#issuecomment-2569208746.

Because the two techniques return different results, I had to put a shim in between reading and output for the column names.

But, it now shows column names in laravel 11 projects.

Fixes #70

### CODE REVIEW

File: src/GraphBuilder.php [hunk 1]
```diff
@@ -61,11 +67,18 @@ protected function getModelLabel(EloquentModel $model, string $label)
         if (config('erd-generator.use_db_schema')) {
             $columns = $this->getTableColumnsFromModel($model);
             foreach ($columns as $column) {
-                $label = $column->getName();
+                if (is_object($column)) {
+                    $name = $column->getName();
+                    $typeName = $column->getType()->getName();
+                } else { // it's an array!
+                    $name = $column['name'];
```
Comment (mechelon) [inline src/GraphBuilder.php:74]: Please still check if the array key exists

**Review by mechelon — CHANGES_REQUESTED** [review]
